(feat) #noticket Added check for prevent fakeAPI.js commits

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -17,6 +17,11 @@ if [ "$files" != "" ]; then
           exit 1
         fi
     fi
+
+    if [[ "$f" =~ fakeAPI.js$ ]]; then
+      echo "ERROR: \"${f}\" should not be committed"
+      exit 1
+    fi
   done
 fi
 exit 0
